// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtwwhngipyqdatruslor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0d3dobmdpcHlxZGF0cnVzbG9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NzIxNTcsImV4cCI6MjA1OTA0ODE1N30.KHQYk5_xiEa0H7BTVls6C1OnoVStfXjk3fNFSfT_c5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);